GET http://localhost:8080/api/posts

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post"
}

###

GET http://localhost:8080/api/posts/1

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 3,
  "title": "Updated New Post",
  "content": "Updated"
}

###

DELETE http://localhost:8080/api/posts/4